pipeline {
    agent {
        docker {
            image 'fredysa/nodejstest'
            args '-p 3000:3000'
            args '-w /app'
            args '-u root' 
            args '-p 8080:8080'
            args '-v /var/run/docker.sock:/var/run/docker.sock'

        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
